- selenoid.go
- service/docker.go
- service/driver.go
- service/service.go
- utils_test.go
> Improved logging

- config/config.go
- config_test.go
- main.go
- selenoid.go
- service/docker.go
- service/driver.go
- service/service.go
- session/session.go
- utils_test.go
Rebased from aandryashin/master.
> Ability to proxy VNC port (fixes #52)

- .travis.yml
should be defined `GITHUB_TOKEN` as travis env var first
> autoupload binaries

- selenoid.go
> close vnc client connection on container remove

- main.go
- service/docker.go
- service/service.go
- session/session.go
Sometimes a hostname is required other than "localhost"
> add parameter, hostname of container

- service/docker.go
- session/session.go
This includes startup method refactoring to make it smaller.
> Added ability to pass container hosts entries as capability (fixes #236)

- service/docker.go
Исправил передачу capability - name в параметр tag, опций log-opt, Docker
> FIX: log tag value: Name -> TestName

- Gopkg.lock
- selenoid.go
relates https://github.com/aerokube/selenoid-ui/issues/98
> right demultiplex for docker logs

- docs/special-capabilities.adoc
Added info about android emulator skins, and give an example for set exact skin throw capablities
@vania-pooh
> Added info about android emulator skins

- docs/browser-image-information.adoc
fixes aerokube/selenoid-images#102
> Added Firefox 66.0 image information

- docs/quick-start-guide.adoc
Updated NOTE about path in opera images, since they also require path as "/"
> Updated NOTE about path in opera images

- docs/browser-image-information.adoc
fixes aerokube/selenoid-images#183
> Added Opera 63.0 image information

- docs/browser-image-information.adoc
fixes aerokube/selenoid-images#245
> Bump Chrome 81.0 and Chromedriver versions

- Dockerfile
> Reverted Dockerfile USER change

- docs/starting-selenoid-manually.adoc
> Fix broken command in documentation

- docs/faq.adoc
- docs/starting-selenoid-manually.adoc
- selenoid.go
> New safaridriver interaction fix

- selenoid.go
Fix for https://github.com/aerokube/selenoid/issues/1112
> Prevent unwanted timeout function call

- selenoid.go
> Fixed file upload.

- selenoid.go
- selenoid_test.go
Implement `se:cdp` capability to be able to connect from playwright. Related PR to pwt - https://github.com/microsoft/playwright/pull/23341.
fixes #1063
> feat: support "se:cdp" capability

- docs/faq.adoc
FAQ VNC consumption CPU on Redhat/Centos
> VNC RedHat doc
